#:property LangVersion=latest
#:property Nullable=enable
#:property ImplicitUsings=enable
// scripts/MeasureBuild.cs — .NET 10 file-based program.
//
// What this measures (all via `just` recipes so CLAUDE.md rule 1 is honoured):
//   - Cold rebuild   : (clean -> restore -> rebuild) × N → median seconds
//   - Warm incremental: build × N                       → median seconds
//   - Test           : test-fast × N                    → median seconds
// Plus one-shot captures:
//   - MSBuild binary log + PerformanceSummary  (just measure-binlog)
//   - Per-analyzer time report                 (just analyzer-report)
//   - MSBuild BuildCheck                       (just lint-build)
//
// Output:
//   docs/perf/baseline-<yyyy-MM-dd>.md          — when invoked without --label
//   docs/perf/baseline-<yyyy-MM-dd>-<slug>.md   — when --label is set (per-Phase runs
//                                                 keep their own file, no overwrite)
//   artifacts/perf/{perf-summary,analyzer-report,build-check}.txt
//   artifacts/perf/build.binlog                 — open with MSBuild Binary Log Viewer
//
// Run: `just measure` (or `dotnet run scripts/MeasureBuild.cs -- --iterations 5`).

using System.Diagnostics;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;

var iterations = 5;
string? label = null;
for (var i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--iterations" or "-n" when i + 1 < args.Length:
            iterations = int.Parse(args[++i], CultureInfo.InvariantCulture);
            break;
        case "--label" or "-l" when i + 1 < args.Length:
            label = args[++i];
            break;
        case "--help" or "-h":
            Console.WriteLine("Usage: just measure   (or: dotnet run scripts/MeasureBuild.cs -- --iterations N --label TEXT)");
            return 0;
        default:
            break;
    }
}

// `just measure` runs us from the repo root; that's our anchor.
// (AppContext.BaseDirectory points into the SDK's file-based-program tmp dir, so it's unusable here.)
var repoRoot = Directory.GetCurrentDirectory();
var artifacts = Path.Combine(repoRoot, "artifacts", "perf");
var docsDir = Path.Combine(repoRoot, "docs", "perf");
var today = DateTime.Now.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
var labelSlug = label is null ? "" : "-" + Regex.Replace(label.ToLowerInvariant(), "[^a-z0-9]+", "-").Trim('-');
var baselineMd = Path.Combine(docsDir, $"baseline-{today}{labelSlug}.md");

Directory.CreateDirectory(artifacts);
Directory.CreateDirectory(docsDir);

WriteHeader("measure-build");
Console.WriteLine($"  repo       : {repoRoot}");
Console.WriteLine($"  iterations : {iterations}");
Console.WriteLine($"  output     : {baselineMd}");
if (label is not null)
{
    Console.WriteLine($"  label      : {label}");
}
Console.WriteLine();

// ── Cold rebuild × N first — its `just clean` would otherwise wipe artifacts/ ──
var cold = Measure("cold-rebuild", iterations, () =>
{
    Just("clean");
    Just("restore");
    Just("rebuild");
});

// The last cold iteration leaves a fresh build; warm-incremental runs on it.
var warm = Measure("warm-incremental", iterations, () => Just("build"));
var test = Measure("test-fast", iterations, () => Just("test-fast"));

// ── Diagnostic one-shots — safe now that cold is done ──────────────────────────
// (Re-create artifacts/perf because the last cold iteration's clean removed it.)
Directory.CreateDirectory(artifacts);

WriteStep("Capturing binlog + PerformanceSummary…");
Just("measure-binlog", Path.Combine(artifacts, "perf-summary.txt"), ignoreExitCode: false);

WriteStep("Capturing analyzer report…");
Just("analyzer-report", Path.Combine(artifacts, "analyzer-report.txt"), ignoreExitCode: false);

WriteStep("Running MSBuild BuildCheck (-check)…");
// BuildCheck can exit non-zero when findings are emitted; we still want to capture the output.
Just("lint-build", Path.Combine(artifacts, "build-check.txt"), ignoreExitCode: true);

// ── Extract analyzer top-N rows ────────────────────────────────────────────────
var analyzerTop = ReadAnalyzerTop(Path.Combine(artifacts, "analyzer-report.txt"), maxRows: 15);

// ── Write baseline markdown ────────────────────────────────────────────────────
var md = new StringBuilder();
md.Append("# Build perf baseline — ").AppendLine(today);
if (label is not null)
{
    md.AppendLine();
    md.Append("**Label:** ").AppendLine(label);
}
md.AppendLine();
md.Append("Generated by `scripts/MeasureBuild.cs` (median of ").Append(iterations.ToString(CultureInfo.InvariantCulture)).AppendLine(" runs).");
md.AppendLine();
md.AppendLine("## Timings (seconds)");
md.AppendLine();
md.AppendLine("| Scenario | Median | Min | Max | Samples |");
md.AppendLine("|---|---:|---:|---:|---|");
foreach (var row in new[] { cold, warm, test })
{
    var samples = string.Join(", ", row.Samples.Select(s => s.ToString("0.000", CultureInfo.InvariantCulture)));
    md.Append(CultureInfo.InvariantCulture, $"| {row.Name} | {row.Median:0.000} | {row.Min:0.000} | {row.Max:0.000} | {samples} |").AppendLine();
}
md.AppendLine();
md.AppendLine("## Top analyzers by time (summed across projects)");
md.AppendLine();
if (analyzerTop.Count > 0)
{
    md.AppendLine("| Seconds | Analyzer package |");
    md.AppendLine("|---:|---|");
    foreach (var (seconds, name) in analyzerTop)
    {
        md.Append(CultureInfo.InvariantCulture, $"| {seconds:0.000} | `{name}` |").AppendLine();
    }
}
else
{
    md.AppendLine("_(see `artifacts/perf/analyzer-report.txt` — parser found no rows)_");
}
md.AppendLine();
md.AppendLine("## Artifacts");
md.AppendLine();
md.AppendLine("- `artifacts/perf/build.binlog` — open with MSBuild Binary Log Viewer for target-level drilldown.");
md.AppendLine("- `artifacts/perf/perf-summary.txt` — MSBuild `/clp:PerformanceSummary` output.");
md.AppendLine("- `artifacts/perf/analyzer-report.txt` — per-analyzer timings (`-p:ReportAnalyzer=true`).");
md.AppendLine("- `artifacts/perf/build-check.txt` — MSBuild `-check` (BuildCheck) findings.");
md.AppendLine();
md.AppendLine("## Environment");
md.AppendLine();
md.Append("- Host: `").Append(Environment.MachineName).AppendLine("`");
md.Append(CultureInfo.InvariantCulture, $"- OS:   `{RuntimeInformation.OSDescription}` ({RuntimeInformation.OSArchitecture})").AppendLine();
md.Append(CultureInfo.InvariantCulture, $"- CPU:  `{Environment.GetEnvironmentVariable("PROCESSOR_IDENTIFIER") ?? "unknown"}` ({Environment.ProcessorCount} logical cores)").AppendLine();
md.Append(CultureInfo.InvariantCulture, $"- .NET: `{Environment.Version}` ({RuntimeInformation.FrameworkDescription})").AppendLine();
md.Append(CultureInfo.InvariantCulture, $"- Date: `{DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss zzz}`").AppendLine();

File.WriteAllText(baselineMd, md.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

// ── Console summary ────────────────────────────────────────────────────────────
Console.WriteLine();
WriteHeader("Summary", ConsoleColor.Green);
foreach (var row in new[] { cold, warm, test })
{
    var samples = string.Join(", ", row.Samples.Select(s => s.ToString("0.000", CultureInfo.InvariantCulture)));
    Console.WriteLine(string.Create(CultureInfo.InvariantCulture, $"  {row.Name,-18} : {row.Median,7:0.000} s   (samples: {samples})"));
}
if (analyzerTop.Count > 0)
{
    Console.WriteLine();
    Console.WriteLine($"  Top {Math.Min(3, analyzerTop.Count)} analyzer packages:");
    foreach (var (seconds, name) in analyzerTop.Take(3))
    {
        Console.WriteLine(string.Create(CultureInfo.InvariantCulture, $"    {seconds,6:0.000} s   {name}"));
    }
}
Console.WriteLine();
WriteColor($"Wrote {baselineMd}", ConsoleColor.Green);
return 0;

// ─── Helpers ──────────────────────────────────────────────────────────────────

static MeasureResult Measure(string name, int count, Action body)
{
    var samples = new List<double>(count);
    for (var i = 1; i <= count; i++)
    {
        WriteColor($"  [{name}] iteration {i}/{count}…", ConsoleColor.DarkGray);
        var sw = Stopwatch.StartNew();
        body();
        sw.Stop();
        samples.Add(Math.Round(sw.Elapsed.TotalSeconds, 3, MidpointRounding.AwayFromZero));
    }
    var sorted = samples.Order().ToList();
    var median = sorted[sorted.Count / 2];
    return new MeasureResult(name, median, sorted[0], sorted[^1], samples);
}

static void Just(string recipe, string? logFile = null, bool ignoreExitCode = false)
{
    var psi = new ProcessStartInfo("just", recipe)
    {
        UseShellExecute = false,
        RedirectStandardOutput = logFile is not null,
        RedirectStandardError = logFile is not null,
        CreateNoWindow = true,
    };

    using var p = Process.Start(psi) ?? throw new InvalidOperationException($"failed to start: just {recipe}");

    if (logFile is not null)
    {
        // Event-based async capture — no Task.WaitAll, no deadlock on full pipe buffers.
        using var writer = new StreamWriter(logFile, append: false, Encoding.UTF8);
        p.OutputDataReceived += (_, e) => { if (e.Data is not null) { writer.WriteLine(e.Data); } };
        p.ErrorDataReceived += (_, e) => { if (e.Data is not null) { writer.WriteLine(e.Data); } };
        p.BeginOutputReadLine();
        p.BeginErrorReadLine();
        p.WaitForExit();
    }
    else
    {
        p.WaitForExit();
    }

    if (p.ExitCode != 0 && !ignoreExitCode)
    {
        throw new InvalidOperationException($"just {recipe} exited with code {p.ExitCode}");
    }
}

static List<(double Seconds, string Name)> ReadAnalyzerTop(string path, int maxRows)
{
    if (!File.Exists(path))
    {
        return [];
    }
    // csc.exe ReportAnalyzer prints, per project, a section like (Japanese locale):
    //         アナライザー実行の合計時間: 0.303 秒。
    //         時間 (秒)    %   アナライザー
    //         0.102   33   Microsoft.VisualStudio.Threading.Analyzers.CSharp, Version=…
    //         0.096   31      Microsoft.VisualStudio.Threading.Analyzers.CSharpVSTHRD110… (VSTHRD110)
    //         …
    //         並列実行が有効になっていないアナライザー:
    //
    // English locale uses "Time (s)" and "Analyzers that did not run in parallel".
    // We sum only the package-level rows (name contains "Version=") across every project.

    var totals = new Dictionary<string, double>(StringComparer.Ordinal);
    var inTable = false;
    const RegexOptions opts = RegexOptions.Compiled | RegexOptions.ExplicitCapture;
    var headerRegex = new Regex(@"(?:時間\s*\(秒\)|Time\s*\(s\))\s+%", opts);
    var endRegex = new Regex(@"(?:並列実行が有効になっていないアナライザー|Analyzers that did not run in parallel)", opts);
    var rowRegex = new Regex(@"^(?<sec><?[0-9]+(?:\.[0-9]+)?)\s+<?[0-9]+\s+(?<name>.+?)$", opts);

    foreach (var raw in File.ReadLines(path))
    {
        var line = raw.TrimEnd();
        var t = line.TrimStart();
        if (t.Length == 0)
        {
            continue;
        }
        if (headerRegex.IsMatch(t))
        {
            inTable = true;
            continue;
        }
        if (endRegex.IsMatch(t))
        {
            inTable = false;
            continue;
        }
        if (!inTable)
        {
            continue;
        }

        var m = rowRegex.Match(t);
        if (!m.Success)
        {
            inTable = false;
            continue;
        }
        var name = m.Groups["name"].Value;
        // Package-level rows contain "Version=...". Sub-rows (single rules) don't.
        if (!name.Contains("Version=", StringComparison.Ordinal))
        {
            continue;
        }
        var comma = name.IndexOf(',', StringComparison.Ordinal);
        var packageName = comma > 0 ? name[..comma] : name;

        var secStr = m.Groups["sec"].Value.TrimStart('<');
        if (!double.TryParse(secStr, NumberStyles.Float, CultureInfo.InvariantCulture, out var seconds))
        {
            continue;
        }
        totals.TryGetValue(packageName, out var existing);
        totals[packageName] = existing + seconds;
    }

    return [.. totals
        .OrderByDescending(kv => kv.Value)
        .Take(maxRows)
        .Select(kv => (kv.Value, kv.Key))];
}

static void WriteHeader(string text, ConsoleColor color = ConsoleColor.Cyan)
{
    var prev = Console.ForegroundColor;
    Console.ForegroundColor = color;
    Console.WriteLine($"── {text} ──");
    Console.ForegroundColor = prev;
}

static void WriteStep(string text)
{
    var prev = Console.ForegroundColor;
    Console.ForegroundColor = ConsoleColor.Cyan;
    Console.WriteLine($"▶ {text}");
    Console.ForegroundColor = prev;
}

static void WriteColor(string text, ConsoleColor color)
{
    var prev = Console.ForegroundColor;
    Console.ForegroundColor = color;
    Console.WriteLine(text);
    Console.ForegroundColor = prev;
}

file readonly record struct MeasureResult(string Name, double Median, double Min, double Max, IReadOnlyList<double> Samples);
